spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/wanted1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  header: Authorization
  secret: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M
  token-validity-in-seconds: 86400