spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
        enabled: true

jwt:
  header: Authorization
  secret: c29jaWFsLW1lZGlhLWludGVncmF0aW9uLWZlZWQtcHJvamVjdA==
  expiration:
    access: 86400
    refresh: 864000