spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
        enabled: true

jwt:
  header: Authorization
  secret: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M
  token-validity-in-seconds: 86400