spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: # Gmail 계정
    password: # Gmail 앱 패스워드
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)

  jpa:
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true

jwt:
  header: Authorization
  secret: c29jaWFsLW1lZGlhLWludGVncmF0aW9uLWZlZWQtcHJvamVjdA==
  expiration:
    access: 86400
    refresh: 864000